import type { Car, Contact } from "./types"

export const mockCars: Car[] = [
  {
    id: "1",
    brand: "Toyota",
    model: "Corolla",
    year: 2020,
    price: 285000,
    mileage: 45000,
    transmission: "Automática",
    fuelType: "Gasolina",
    color: "Blanco",
    description: "Toyota Corolla en excelente estado, único dueño, servicios en agencia, factura original.",
    images: ["/toyota-corolla-blanco-2020.jpg"],
    location: "Ciudad de México",
    sellerId: "user1",
    sellerName: "Juan Pérez",
    sellerPhone: "55-1234-5678",
    createdAt: new Date("2024-01-15"),
    featured: true,
    verified: true, // agregando estado verificado
  },
  {
    id: "2",
    brand: "Honda",
    model: "Civic",
    year: 2019,
    price: 295000,
    mileage: 52000,
    transmission: "Manual",
    fuelType: "Gasolina",
    color: "Gris",
    description: "Honda Civic deportivo, excelente rendimiento, llantas nuevas, sistema de sonido premium.",
    images: ["/honda-civic-gris-2019.jpg"],
    location: "Guadalajara",
    sellerId: "user2",
    sellerName: "María González",
    sellerPhone: "33-9876-5432",
    createdAt: new Date("2024-01-20"),
    featured: true,
    verified: true, // agregando estado verificado
  },
  {
    id: "3",
    brand: "Nissan",
    model: "Versa",
    year: 2021,
    price: 235000,
    mileage: 28000,
    transmission: "Automática",
    fuelType: "Gasolina",
    color: "Negro",
    description: "Nissan Versa como nuevo, poco kilometraje, aire acondicionado, bolsas de aire.",
    images: ["/nissan-versa-negro-2021.jpg"],
    location: "Monterrey",
    sellerId: "user3",
    sellerName: "Carlos Ramírez",
    sellerPhone: "81-5555-1234",
    createdAt: new Date("2024-02-01"),
    verified: false, // vendedor no verificado
  },
  {
    id: "4",
    brand: "Volkswagen",
    model: "Jetta",
    year: 2018,
    price: 245000,
    mileage: 68000,
    transmission: "Automática",
    fuelType: "Gasolina",
    color: "Azul",
    description: "VW Jetta en muy buen estado, mantenimiento al día, interiores impecables.",
    images: ["/volkswagen-jetta-azul-2018.jpg"],
    location: "Puebla",
    sellerId: "user4",
    sellerName: "Ana Martínez",
    sellerPhone: "22-3333-4567",
    createdAt: new Date("2024-02-05"),
    verified: true, // agregando estado verificado
  },
  {
    id: "5",
    brand: "Mazda",
    model: "CX-5",
    year: 2022,
    price: 485000,
    mileage: 15000,
    transmission: "Automática",
    fuelType: "Gasolina",
    color: "Rojo",
    description: "Mazda CX-5 SUV premium, pantalla touch, cámara de reversa, sensores de estacionamiento.",
    images: ["/mazda-cx5-rojo-suv-2022.jpg"],
    location: "Querétaro",
    sellerId: "user5",
    sellerName: "Roberto Silva",
    sellerPhone: "44-7777-8901",
    createdAt: new Date("2024-02-10"),
    featured: true,
    verified: true, // agregando estado verificado
  },
  {
    id: "6",
    brand: "Chevrolet",
    model: "Aveo",
    year: 2019,
    price: 165000,
    mileage: 72000,
    transmission: "Manual",
    fuelType: "Gasolina",
    color: "Plata",
    description: "Chevrolet Aveo económico, ideal para ciudad, bajo consumo de combustible.",
    images: ["/chevrolet-aveo-plata-2019.jpg"],
    location: "Tijuana",
    sellerId: "user6",
    sellerName: "Laura Hernández",
    sellerPhone: "66-4444-5678",
    createdAt: new Date("2024-02-12"),
    verified: false, // vendedor no verificado
  },
]

export const mockContacts: Contact[] = [
  {
    id: "contact1",
    carId: "1",
    buyerId: "buyer1",
    buyerName: "Pedro López",
    buyerEmail: "pedro@email.com",
    buyerPhone: "55-9999-1234",
    message: "Hola, me interesa mucho tu Toyota Corolla. ¿Está disponible aún? ¿Puedo verlo este fin de semana?",
    createdAt: new Date("2024-02-15"),
    status: "new",
  },
  {
    id: "contact2",
    carId: "1",
    buyerId: "buyer2",
    buyerName: "Sofia Rodríguez",
    buyerEmail: "sofia@email.com",
    buyerPhone: "55-8888-5678",
    message: "¿Cuál es el historial de mantenimiento? ¿Tiene cambio de aceite reciente?",
    createdAt: new Date("2024-02-14"),
    status: "new",
    offeredPrice: 280000,
  },
  {
    id: "contact3",
    carId: "1",
    buyerId: "buyer3",
    buyerName: "Miguel Ángeles",
    buyerEmail: "miguel@email.com",
    buyerPhone: "55-7777-9012",
    message: "Excelente auto, ya voy en camino a verlo",
    createdAt: new Date("2024-02-13"),
    status: "read",
  },
  {
    id: "contact4",
    carId: "2",
    buyerId: "buyer4",
    buyerName: "Diana Castillo",
    buyerEmail: "diana@email.com",
    buyerPhone: "33-6666-3456",
    message: "¿Aceptas cambio por otro vehículo? Tengo un Jetta 2017",
    createdAt: new Date("2024-02-14"),
    status: "new",
  },
  {
    id: "contact5",
    carId: "2",
    buyerId: "buyer5",
    buyerName: "Ricardo Torres",
    buyerEmail: "ricardo@email.com",
    buyerPhone: "33-5555-7890",
    message: "¿Es precio fijo o hay espacio para negociar?",
    createdAt: new Date("2024-02-12"),
    status: "read",
  },
]
